#!/usr/bin/env python3
"""
HD995 — Client-side notification clean sweep. Removes ALL client-side email
notification code now that every path (task, note, ticket reply/assign, RFC,
Contact Client) is handled server-side by NotificationService (slices 1-5).

Removes the three _notify methods + callers, CreateTicket._notifyContactClient +
caller, the RFC client notify calls, PageBase._sendNotificationEmail /
_determineNotificationType, TicketLoader's window.TicketEmailData publish, and
deletes wwwroot/js/Components/Emails/Emails.js plus its _Layout script tag.

Each removal is an exact verified byte block (asserted to appear exactly once).
After removal all 8 touched JS files pass `node --check` with zero remaining
references to the removed functions.

ASSUMES the full notification stack is merged (email-routing-fix, contactclient,
server slices 1-5). Idempotent. Usage: python3 apply_notification_cleanup.py [root]
"""

import base64
import os
import sys

ROOT = sys.argv[1] if len(sys.argv) > 1 else '.'

# (key, relative_path, base64_block_to_remove)
REMOVALS = [
    ('ticketsave_method', 'wwwroot/js/Ticket/Features/TicketSave.js', 'ICAgIC8vIFRpY2tldE9wZXJhdGlvbnM7IHRoZSBvbGQgbW9kYWwgKyBwYWdlLXJlbG9hZCBmZWVkYmFjayBpcyBpbnRlbnRpb25hbGx5CiAgICAvLyBkcm9wcGVkICh0aGUgaW5saW5lICdUaWNrZXQgc2F2ZWQnIHRvYXN0IHJlcGxhY2VzIGl0KSwgc28gd2Ugc2VuZCB0aGUKICAgIC8vIG1haWwgZGlyZWN0bHkgaW5zdGVhZCBvZiBnb2luZyB0aHJvdWdoIFNlbmROb3RpZmljYXRpb25FbWFpbC4KICAgIC8vIE5PVEU6IHZlcmlmeSBhZ2FpbnN0IHRoZSBsaXZlIG1haWwgZmxvdyDigJQgY2FuJ3QgYmUgZXhlcmNpc2VkIGZyb20gaGVyZS4KICAgIGFzeW5jIF9ub3RpZnkoc2F2ZVJlc3VsdCwgdGlja2V0SWQpIHsKICAgICAgICBpZiAodHlwZW9mIEJ1aWxkRW1haWxBZGRyZXNzTGlzdCAhPT0gJ2Z1bmN0aW9uJykgcmV0dXJuOwoKICAgICAgICBjb25zdCBuZXdUZWNoID0gc2Vzc2lvblN0b3JhZ2UuZ2V0SXRlbShTVE9SQUdFX0tFWVMuTkVXX0FTU0lHTkVEX1RFQ0gpOwogICAgICAgIGNvbnN0IG9sZFRlY2ggPSBzZXNzaW9uU3RvcmFnZS5nZXRJdGVtKFNUT1JBR0VfS0VZUy5PTERfQVNTSUdORURfVEVDSCk7CgogICAgICAgIGNvbnN0IHNlcnZlclR5cGUgPSBBcnJheS5pc0FycmF5KHNhdmVSZXN1bHQpID8gc2F2ZVJlc3VsdFswXSA6IHNhdmVSZXN1bHQ7CiAgICAgICAgY29uc3Qgbm90aWZ5VHlwZSA9IHNlcnZlclR5cGUgPT09ICdVcGRhdGUnICYmIG5ld1RlY2ggIT09IG9sZFRlY2gKICAgICAgICAgICAgPyAnQXNzaWduZWQnCiAgICAgICAgICAgIDogc2VydmVyVHlwZTsKICAgICAgICBpZiAoIW5vdGlmeVR5cGUpIHJldHVybjsKCiAgICAgICAgY29uc3QgaWQgPSB0aWNrZXRJZCA/PyAoQXJyYXkuaXNBcnJheShzYXZlUmVzdWx0KSA/IHNhdmVSZXN1bHRbMV0gOiBudWxsKTsKICAgICAgICBjb25zdCB1c2VybmFtZSA9IHNlc3Npb25TdG9yYWdlLmdldEl0ZW0oU1RPUkFHRV9LRVlTLlVTRVJfTkFNRSk7CgogICAgICAgIHRyeSB7CiAgICAgICAgICAgIGNvbnN0IGFkZHJlc3MgPSBhd2FpdCBCdWlsZEVtYWlsQWRkcmVzc0xpc3QoCiAgICAgICAgICAgICAgICBub3RpZnlUeXBlLCAnVGlja2V0JywgbmV3VGVjaCwgdXNlcm5hbWUsIGdldEl0ZW1Pd25lcigpCiAgICAgICAgICAgICk7CiAgICAgICAgICAgIGlmICghYWRkcmVzcykgcmV0dXJuOwogICAgICAgICAgICBhd2FpdCBTZW5kTWFpbE1lc3NhZ2UoCiAgICAgICAgICAgICAgICBhZGRyZXNzLAogICAgICAgICAgICAgICAgQ3JlYXRlTWVzc2FnZVN1YmplY3Qobm90aWZ5VHlwZSwgJ1RpY2tldCcsIGlkKSwKICAgICAgICAgICAgICAgIEJ1aWxkRW1haWxCb2R5KG5vdGlmeVR5cGUsICdUaWNrZXQnLCBpZCkKICAgICAgICAgICAgKTsKICAgICAgICB9IGNhdGNoIChlcnIpIHsKICAgICAgICAgICAgY29uc29sZS5lcnJvcignU2F2ZS5fbm90aWZ5OicsIGVycik7CiAgICAgICAgfQogICAgfSwK'),
    ('ticketsave_caller', 'wwwroot/js/Ticket/Features/TicketSave.js', 'CiAgICAgICAgICAgIGF3YWl0IFNhdmUuX25vdGlmeShkYXRhLCBwYXlsb2FkLlRpY2tldElEKTsK'),
    ('messagepanel_method', 'wwwroot/js/Components/Messages/MessagePanel.js', 'ICAgIC8vIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gIE5vdGlmeSAgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSAvLwogICAgLy8gQSBjbGllbnQtdmlzaWJsZSBtZXNzYWdlIGlzIGEgIlJlc3BvbmRlZCIgZXZlbnQgb24gdGhlIHRpY2tldC4gU2VuZCB0aGUKICAgIC8vIG5vdGlmaWNhdGlvbiBtYWlsIGRpcmVjdGx5ICh0b2FzdCBVSSAtLSBza2lwIHRoZSBtb2RhbCB0aGF0CiAgICAvLyBTZW5kTm90aWZpY2F0aW9uRW1haWwgc2hvd3MpLCBtaXJyb3JpbmcgVGlja2V0U2F2ZS5fbm90aWZ5LiBUaGUgcmVjaXBpZW50CiAgICAvLyBsb2dpYyAoYW5kIHRoZSAibm8gZW1haWwgZm9yIGludGVybmFsL0dvdnRlY2ggYXV0aG9yaXRpZXMiIGNhc2UpIGxpdmVzIGluCiAgICAvLyBCdWlsZEVtYWlsQWRkcmVzc0xpc3QuIEZpcmUtYW5kLWZvcmdldDogYSBtYWlsIGZhaWx1cmUgbXVzdCBub3QgYmxvY2sgdGhlCiAgICAvLyBzZW5kLCBhbmQgaXQgaGFzIGl0cyBvd24gZXJyb3IgaGFuZGxpbmcuCiAgICAvLyBOT1RFOiB1bnRlc3RhYmxlIGZyb20gaGVyZSAtLSB2ZXJpZnkgYWdhaW5zdCB0aGUgbGl2ZSBtYWlsIGZsb3cuCiAgICBhc3luYyBmdW5jdGlvbiBfbm90aWZ5KCkgewogICAgICAgIGlmICh0eXBlb2YgQnVpbGRFbWFpbEFkZHJlc3NMaXN0ICE9PSAnZnVuY3Rpb24nKSByZXR1cm47CiAgICAgICAgdHJ5IHsKICAgICAgICAgICAgY29uc3QgbmV3VGVjaCA9IHNlc3Npb25TdG9yYWdlLmdldEl0ZW0oU1RPUkFHRV9LRVlTLk5FV19BU1NJR05FRF9URUNIKTsKICAgICAgICAgICAgY29uc3QgdXNlcm5hbWUgPSBzZXNzaW9uU3RvcmFnZS5nZXRJdGVtKFNUT1JBR0VfS0VZUy5VU0VSX05BTUUpOwoKICAgICAgICAgICAgY29uc3QgYWRkcmVzcyA9IGF3YWl0IEJ1aWxkRW1haWxBZGRyZXNzTGlzdCgKICAgICAgICAgICAgICAgICdSZXNwb25kZWQnLCAnVGlja2V0JywgbmV3VGVjaCwgdXNlcm5hbWUsIGdldEl0ZW1Pd25lcigpCiAgICAgICAgICAgICk7CiAgICAgICAgICAgIGlmICghYWRkcmVzcykgcmV0dXJuOwoKICAgICAgICAgICAgYXdhaXQgU2VuZE1haWxNZXNzYWdlKAogICAgICAgICAgICAgICAgYWRkcmVzcywKICAgICAgICAgICAgICAgIENyZWF0ZU1lc3NhZ2VTdWJqZWN0KCdSZXNwb25kZWQnLCAnVGlja2V0JywgU3RhdGUudGlja2V0SWQpLAogICAgICAgICAgICAgICAgQnVpbGRFbWFpbEJvZHkoJ1Jlc3BvbmRlZCcsICdUaWNrZXQnLCBTdGF0ZS50aWNrZXRJZCkKICAgICAgICAgICAgKTsKICAgICAgICB9IGNhdGNoIChlcnIpIHsKICAgICAgICAgICAgY29uc29sZS5lcnJvcignTWVzc2FnZXNQYW5lbC5fbm90aWZ5OicsIGVycik7CiAgICAgICAgfQogICAgfQo='),
    ('messagepanel_caller', 'wwwroot/js/Components/Messages/MessagePanel.js', 'CiAgICAgICAgICAgIC8vIE5vdGlmeSB0aGUgY2xpZW50IHRoYXQgYSB2aXNpYmxlIHVwZGF0ZSB3YXMgcG9zdGVkLgogICAgICAgICAgICBfbm90aWZ5KCk7'),
    ('tasks_method', 'wwwroot/js/Tasks/Features/Tasks.js', 'ICAgIC8vIEVtYWlsIHRoZSB0aWNrZXQncyB3YXRjaGVycyBhZnRlciBhIHRhc2sgc2F2ZS4gUG9ydGVkIGZyb20gdGhlIHJldGlyZWQKICAgIC8vIFRhc2tPcGVyYXRpb25zOyB0aGUgbWFpbCBpcyBzZW50IGRpcmVjdGx5IGJlY2F1c2UgdGhlIG9sZCBtb2RhbCArIHBhZ2UKICAgIC8vIHJlbG9hZCBpcyBub3QgcGFydCBvZiB0aGUgbmV3IGlubGluZS10b2FzdCBmbG93LgogICAgLy8gTk9URTogdGhlIG5ldyBlZGl0b3IgZG9lcyBub3QgdHJhY2sgTkVXL09MRCBhc3NpZ25lZC10ZWNoIHNlc3Npb24ga2V5cywgc28KICAgIC8vIHRoZSAnQXNzaWduZWQnIChyZS1hc3NpZ25tZW50KSB0eXBlIGlzIG5vdCBkZXRlY3RlZCB0aGUgd2F5IHRoZSBvbGQgZm9ybQogICAgLy8gZGlkIOKAlCB0aGUgc2VydmVyJ3MgYmFzZSB0eXBlIGlzIHVzZWQgaW5zdGVhZC4gVmVyaWZ5IHJlY2lwaWVudHMgYWdhaW5zdAogICAgLy8gdGhlIGxpdmUgbWFpbCBmbG93OyBjYW4ndCBiZSBleGVyY2lzZWQgZnJvbSBoZXJlLgogICAgYXN5bmMgZnVuY3Rpb24gX25vdGlmeVRhc2soc2F2ZVJlc3VsdCkgewogICAgICAgIGlmICh0eXBlb2YgQnVpbGRFbWFpbEFkZHJlc3NMaXN0ICE9PSAnZnVuY3Rpb24nKSByZXR1cm47CgogICAgICAgIGNvbnN0IG5ld1RlY2ggPSBzZXNzaW9uU3RvcmFnZS5nZXRJdGVtKFNUT1JBR0VfS0VZUy5ORVdfQVNTSUdORURfVEVDSCk7CiAgICAgICAgY29uc3Qgb2xkVGVjaCA9IHNlc3Npb25TdG9yYWdlLmdldEl0ZW0oU1RPUkFHRV9LRVlTLk9MRF9BU1NJR05FRF9URUNIKTsKCiAgICAgICAgY29uc3Qgc2VydmVyVHlwZSA9IEFycmF5LmlzQXJyYXkoc2F2ZVJlc3VsdCkgPyBzYXZlUmVzdWx0WzBdIDogc2F2ZVJlc3VsdDsKICAgICAgICBjb25zdCBub3RpZnlUeXBlID0gc2VydmVyVHlwZSA9PT0gJ1VwZGF0ZScgJiYgbmV3VGVjaCAhPT0gb2xkVGVjaAogICAgICAgICAgICA/ICdBc3NpZ25lZCcKICAgICAgICAgICAgOiBzZXJ2ZXJUeXBlOwogICAgICAgIGlmICghbm90aWZ5VHlwZSkgcmV0dXJuOwoKICAgICAgICBjb25zdCBpZCA9IFN0YXRlLnRpY2tldElkID8/IChBcnJheS5pc0FycmF5KHNhdmVSZXN1bHQpID8gc2F2ZVJlc3VsdFsxXSA6IG51bGwpOwogICAgICAgIGNvbnN0IHVzZXJuYW1lID0gc2Vzc2lvblN0b3JhZ2UuZ2V0SXRlbShTVE9SQUdFX0tFWVMuVVNFUl9OQU1FKTsKCiAgICAgICAgdHJ5IHsKICAgICAgICAgICAgY29uc3QgYWRkcmVzcyA9IGF3YWl0IEJ1aWxkRW1haWxBZGRyZXNzTGlzdChub3RpZnlUeXBlLCAnVGFzaycsIG5ld1RlY2gsIHVzZXJuYW1lLCBnZXRJdGVtT3duZXIoKSk7CiAgICAgICAgICAgIGlmICghYWRkcmVzcykgcmV0dXJuOwogICAgICAgICAgICBhd2FpdCBTZW5kTWFpbE1lc3NhZ2UoCiAgICAgICAgICAgICAgICBhZGRyZXNzLAogICAgICAgICAgICAgICAgQ3JlYXRlTWVzc2FnZVN1YmplY3Qobm90aWZ5VHlwZSwgJ1Rhc2snLCBpZCksCiAgICAgICAgICAgICAgICBCdWlsZEVtYWlsQm9keShub3RpZnlUeXBlLCAnVGFzaycsIGlkKQogICAgICAgICAgICApOwogICAgICAgIH0gY2F0Y2ggKGVycikgewogICAgICAgICAgICBjb25zb2xlLmVycm9yKCdUYXNrcy5fbm90aWZ5VGFzazonLCBlcnIpOwogICAgICAgIH0KICAgIH0K'),
    ('tasks_caller', 'wwwroot/js/Tasks/Features/Tasks.js', 'ICAgICAgICAgICAgX25vdGlmeVRhc2soZGF0YSk7Cg=='),
    ('createticket_method', 'wwwroot/js/Ticket/Pages/CreateTicket.js', 'ICAgIC8vIENvbnRhY3QgQ2xpZW50IHRpY2tldHMgKHR5cGUgMTIpOiB0aGUgc2VydmVyIG1ha2VzIHRoZSBjbGllbnQgdGhlDQogICAgLy8gdGlja2V0J3MgcmFpc2VyIGFuZCB0aGUgY3JlYXRpbmcgc3RhZmYgbWVtYmVyIHRoZSBhc3NpZ25lZCB0ZWNoLg0KICAgIC8vIE5vdGlmeSBib3RoIC0tIHRoZSBjbGllbnQgdGhhdCBhIHRpY2tldCB3YXMgcmFpc2VkIGZvciB0aGVtLCBhbmQNCiAgICAvLyB0aGUgYXNzaWduZWQgdGVjaC4gY29udGFjdENsaWVudCBpcyAnYXV0aG9yaXR5fGNsaWVudElkJy4NCiAgICBhc3luYyBfbm90aWZ5Q29udGFjdENsaWVudCh0aWNrZXRJZCwgY29udGFjdENsaWVudCkgew0KICAgICAgICBpZiAodHlwZW9mIEdldFVzZXJFbWFpbEFkZHJlc3MgIT09ICdmdW5jdGlvbicpIHJldHVybjsNCiAgICAgICAgdHJ5IHsNCiAgICAgICAgICAgIGNvbnN0IFssIGNsaWVudElkXSA9IFN0cmluZyhjb250YWN0Q2xpZW50KS5zcGxpdCgnfCcpOw0KICAgICAgICAgICAgY29uc3QgW2NsaWVudEVtYWlsLCB0ZWNoRW1haWxdID0gYXdhaXQgUHJvbWlzZS5hbGwoWw0KICAgICAgICAgICAgICAgIEdldFVzZXJFbWFpbEFkZHJlc3MoY2xpZW50SWQpLA0KICAgICAgICAgICAgICAgIEdldFVzZXJFbWFpbEFkZHJlc3ModGhpcy51c2VybmFtZSksDQogICAgICAgICAgICBdKTsNCiAgICAgICAgICAgIGNvbnN0IHJlY2lwaWVudHMgPSBbY2xpZW50RW1haWwsIHRlY2hFbWFpbF0uZmlsdGVyKEJvb2xlYW4pOw0KICAgICAgICAgICAgaWYgKCFyZWNpcGllbnRzLmxlbmd0aCkgcmV0dXJuOw0KICAgICAgICAgICAgYXdhaXQgU2VuZE1haWxNZXNzYWdlKA0KICAgICAgICAgICAgICAgIHJlY2lwaWVudHMuam9pbignLCcpLA0KICAgICAgICAgICAgICAgIENyZWF0ZU1lc3NhZ2VTdWJqZWN0KCdDcmVhdGVkRm9yJywgJ1RpY2tldCcsIHRpY2tldElkKSwNCiAgICAgICAgICAgICAgICBCdWlsZEVtYWlsQm9keSgnQ3JlYXRlZEZvcicsICdUaWNrZXQnLCB0aWNrZXRJZCkNCiAgICAgICAgICAgICk7DQogICAgICAgIH0gY2F0Y2ggKGVycikgew0KICAgICAgICAgICAgY29uc29sZS5lcnJvcignQ3JlYXRlVGlja2V0Ll9ub3RpZnlDb250YWN0Q2xpZW50OicsIGVycik7DQogICAgICAgIH0NCiAgICB9DQo='),
    ('createticket_caller', 'wwwroot/js/Ticket/Pages/CreateTicket.js', 'ICAgICAgICBpZiAoY29udGFjdENsaWVudCkgew0KICAgICAgICAgICAgYXdhaXQgdGhpcy5fbm90aWZ5Q29udGFjdENsaWVudChuZXdUaWNrZXRJZCwgY29udGFjdENsaWVudCk7DQogICAgICAgIH0NCg0K'),
    ('rfcsave_block', 'wwwroot/js/RFC/Features/RFCSave.js', 'ICAgICAgICBpZiAodmlzaWJpbGl0eSAmJiAhYXV0b1NhdmUpIHsKICAgICAgICAgICAgLy8gX3NlbmROb3RpZmljYXRpb25FbWFpbCBpbmhlcml0ZWQgZnJvbSBUaWNrZXRCYXNlCiAgICAgICAgICAgIHRoaXMuX3NlbmROb3RpZmljYXRpb25FbWFpbCgnUkZDJywgZGF0YVswXSwgcmZjSWQgPz8gZGF0YVsxXSk7CiAgICAgICAgfQo='),
    ('createrfc_block', 'wwwroot/js/RFC/Pages/CreateRFC.js', 'ICAgICAgICBjb25zdCBhc3NpZ25lZFRlY2ggPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYXNzaWduZWRUZWNoTmFtZScpOw0KICAgICAgICBpZiAoYXNzaWduZWRUZWNoPy5zZWxlY3RlZEluZGV4ID49IDApIHsNCiAgICAgICAgICAgIGNvbnN0IHRlY2hJZCA9IGFzc2lnbmVkVGVjaC5vcHRpb25zW2Fzc2lnbmVkVGVjaC5zZWxlY3RlZEluZGV4XS52YWx1ZTsNCiAgICAgICAgICAgIGNvbnN0IHRlY2hFbWFpbCA9IEdldFVzZXJFbWFpbEFkZHJlc3ModGVjaElkKTsNCiAgICAgICAgICAgIENyZWF0ZUFuZFNlbmRFbWFpbChuZXdSZmNJZCwgJ0Fzc2lnbmVkJywgJ1JGQycsIHRlY2hFbWFpbCwgJycsICcnLCAnJywgJycpOw0KICAgICAgICB9DQo='),
    ('pagebase_methods', 'wwwroot/js/Shared/PageBase.js', 'ICAgIF9kZXRlcm1pbmVOb3RpZmljYXRpb25UeXBlKG9yaWdpbmFsVHlwZSkgew0KICAgICAgICBjb25zdCBuZXdUZWNoID0gc2Vzc2lvblN0b3JhZ2UuZ2V0SXRlbShTVE9SQUdFX0tFWVMuTkVXX0FTU0lHTkVEX1RFQ0gpOw0KICAgICAgICBjb25zdCBvbGRUZWNoID0gc2Vzc2lvblN0b3JhZ2UuZ2V0SXRlbShTVE9SQUdFX0tFWVMuT0xEX0FTU0lHTkVEX1RFQ0gpOw0KDQogICAgICAgIHJldHVybiBvcmlnaW5hbFR5cGUgPT09ICdVcGRhdGUnICYmIG5ld1RlY2ggIT09IG9sZFRlY2gNCiAgICAgICAgICAgID8gJ0Fzc2lnbmVkJw0KICAgICAgICAgICAgOiBvcmlnaW5hbFR5cGU7DQogICAgfQ0KDQogICAgX3NlbmROb3RpZmljYXRpb25FbWFpbCh0eXBlLCBub3RpZmljYXRpb25UeXBlLCBpZCkgew0KICAgICAgICBjb25zdCBmaW5hbFR5cGUgPSB0aGlzLl9kZXRlcm1pbmVOb3RpZmljYXRpb25UeXBlKG5vdGlmaWNhdGlvblR5cGUpOw0KICAgICAgICBTZW5kTm90aWZpY2F0aW9uRW1haWwoDQogICAgICAgICAgICB0eXBlLA0KICAgICAgICAgICAgZmluYWxUeXBlLA0KICAgICAgICAgICAgaWQsDQogICAgICAgICAgICB0aGlzLnVzZXJuYW1lLA0KICAgICAgICAgICAgZ2V0SXRlbU93bmVyKCkNCiAgICAgICAgKTsNCiAgICB9DQo='),
    ('ticketloader_block', 'wwwroot/js/Ticket/Features/TicketLoader.js', 'ICAgICAgICAgICAgLy8gUHVibGlzaCByZXNvbHZlZCByZWNpcGllbnQgZGF0YSBmb3IgdGhlIGVtYWlsIHJvdXRlcgogICAgICAgICAgICAvLyAoRW1haWxzLmpzIGNhbm5vdCBzZWUgdGhpcyBmaWxlLXNjb3BlZCBTdGF0ZSkuIGlzSW50ZXJuYWwKICAgICAgICAgICAgLy8gdXNlcyB0aGUgc2FtZSByZXF1ZXN0LXR5cGUgbGlzdCBhcyBTZXNzaW9uLmlzSW50ZXJuYWwsIHNvCiAgICAgICAgICAgIC8vIGEgJ0NvbnRhY3QgQ2xpZW50JyB0aWNrZXQgY291bnRzIGFzIGEgY2xpZW50IHRpY2tldC4KICAgICAgICAgICAgY29uc3QgSU5URVJOQUxfVFlQRVMgPSBbNCwgOCwgMTAsIDExLCAxNF07CiAgICAgICAgICAgIHdpbmRvdy5UaWNrZXRFbWFpbERhdGEgPSB7CiAgICAgICAgICAgICAgICBjbGllbnRFbWFpbDogZGF0YS5lbWFpbCA/PyAnJywKICAgICAgICAgICAgICAgIHRlY2hFbWFpbDogZGF0YS5hc3NpZ25lZFRlY2hFbWFpbCA/PyAnJywKICAgICAgICAgICAgICAgIGlzSW50ZXJuYWw6IElOVEVSTkFMX1RZUEVTLmluY2x1ZGVzKGRhdGEucmVxdWVzdElEKSwKICAgICAgICAgICAgfTsK'),
]

LAYOUT = 'Views/Shared/_Layout.cshtml'
EMAILS = 'wwwroot/js/Components/Emails/Emails.js'


def main():
    print("HD995 — client-side notification clean sweep")
    print(f"  repo root: {os.path.abspath(ROOT)}")

    for key, rel, b64 in REMOVALS:
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            print(f"  [error] missing {path}")
            sys.exit(1)
        blk = base64.b64decode(b64)
        data = open(path, 'rb').read()
        c = data.count(blk)
        if c == 0:
            print(f"  [skip] {key}: already removed")
            continue
        if c != 1:
            print(f"  [error] {key}: block matched {c} times (expected 1); aborting")
            sys.exit(1)
        open(path, 'wb').write(data.replace(blk, b'', 1))
        print(f"  [write] removed {key}")

    # remove the _Layout script tag (CRLF or LF)
    lay = os.path.join(ROOT, LAYOUT)
    d = open(lay, 'rb').read()
    tag = b'    <script src="~/js/Components/Emails/Emails.js" asp-append-version="true"></script>\r\n'
    if tag not in d:
        tag = tag.replace(b'\r\n', b'\n')
    if tag in d:
        if d.count(tag) != 1:
            print("  [error] _Layout Emails.js tag not unique; aborting")
            sys.exit(1)
        open(lay, 'wb').write(d.replace(tag, b'', 1))
        print("  [write] removed _Layout Emails.js script tag")
    else:
        print("  [skip] _Layout Emails.js tag: already removed")

    # delete Emails.js
    em = os.path.join(ROOT, EMAILS)
    if os.path.exists(em):
        os.remove(em)
        print("  [write] deleted Emails.js")
    else:
        print("  [skip] Emails.js: already deleted")

    print("Done.")
    print("  [note] stage deletions with `git add -A` (Emails.js is removed).")
    print("  [note] run `dotnet build` + a JS smoke test; no client mail code remains.")


if __name__ == '__main__':
    main()
